services:
  TorqIT\FlysystemAzureBundle\AzureFlysystemAdapterFactory:
    resource: 'TorqIT\FlysystemAzureBundle\AzureFlysystemAdapterFactory'
    tags: [ 'shopware.filesystem.factory' ]
    lazy: true
